# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00003bndfmo\tmp\build\80754af9\combined_recipe, last modified Fri Mar  5 13:06:32 2021
# ------------------------------------------------

package:
  name: pylint
  version: 2.7.2
source:
  sha256: 0e21d3b80b96740909d77206d741aa3ce0b06b41be375d92e1f3244a274c1f8a
  url: https://pypi.io/packages/source/p/pylint/pylint-2.7.2.tar.gz
build:
  entry_points:
    - epylint = pylint:run_epylint
    - pylint = pylint:run_pylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar
  number: '1'
  script: C:\\ci\\pylint_1614971312763\\_h_env\\python.exe -m pip install . --no-deps
    --ignore-installed --no-cache-dir -vvv
  string: py39haa95532_1
requirements:
  build: []
  host:
    - atomicwrites 1.4.0 py_0
    - attrs 20.3.0 pyhd3eb1b0_0
    - ca-certificates 2021.1.19 haa95532_0
    - certifi 2020.12.5 py39haa95532_0
    - colorama 0.4.4 pyhd3eb1b0_0
    - importlib-metadata 2.0.0 py_1
    - importlib_metadata 2.0.0 1
    - iniconfig 1.1.1 pyhd3eb1b0_0
    - more-itertools 8.7.0 pyhd3eb1b0_0
    - openssl 1.1.1j h2bbff1b_0
    - packaging 20.9 pyhd3eb1b0_0
    - pip 21.0.1 py39haa95532_0
    - pluggy 0.12.0 py_0
    - py 1.10.0 pyhd3eb1b0_0
    - pyparsing 2.4.7 pyhd3eb1b0_0
    - pytest 6.2.2 py39haa95532_2
    - pytest-runner 5.3.0 pyhd3eb1b0_0
    - python 3.9.1 h6244533_2
    - setuptools 52.0.0 py39haa95532_0
    - six 1.15.0 py39haa95532_0
    - sqlite 3.33.0 h2a8f88b_0
    - toml 0.10.1 py_0
    - tzdata 2020f h52ac0ba_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.36.2 pyhd3eb1b0_0
    - wincertstore 0.2 py39h2bbff1b_0
    - zipp 3.4.0 pyhd3eb1b0_0
    - zlib 1.2.11 h62dcd97_4
  run:
    - astroid >=2.4.0,<=2.5
    - colorama
    - isort >=4.2.5,<6
    - mccabe >=0.6,<0.7
    - python >=3.9,<3.10.0a0
    - toml >=0.7.1
test:
  commands:
    - pylint --help
    - where epylint
    - pyreverse --help
    - symilar --help
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
about:
  description: 'Pylint is a tool that checks for errors in Python code, tries to enforce
    a

    coding standard and looks for code smells.

    '
  dev_url: https://github.com/PyCQA/pylint/
  doc_source_url: https://github.com/PyCQA/pylint/blob/master/doc/index.rst
  doc_url: https://pylint.readthedocs.io/en/latest/
  home: http://www.pylint.org/
  license: GPL-2.0-only
  license_file: COPYING
  summary: python code static checker
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - timleslie
